---
# tasks file for docker_registry
#- name: Stop OLD Registry
#  shell: 'docker service rm registry'

- name: Docker Registry
  shell: 'docker service create --name registry --publish published=5000,target=5000 registry:2'

...
