version: '3.4'
services:

  # FRONT
  chronograf:
    # Full tag list: https://hub.docker.com/r/library/chronograf/tags/
    image: 127.0.0.1:5000/chronograf
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    volumes:
      # Mount for chronograf database
      - /chronograf-data:/var/lib/chronograf
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "8888:8888"

  # MIDDLE
  kapacitor:
    # Full tag list: https://hub.docker.com/r/library/kapacitor/tags/
    image: 127.0.0.1:5000/kapacitor
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    volumes:
      # Mount for kapacitor data directory
      - /kapacitor-data:/var/lib/kapacitor
      # Mount for kapacitor configuration
      - /etc/kapacitor/config:/etc/kapacitor
    ports:
      # The API for Kapacitor is served on port 9092
      - "9092:9092"

  # BACK
  telegraf:
    # Full tag list: https://hub.docker.com/r/library/telegraf/tags/
    image: 127.0.0.1:5000/telegraf
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    volumes:
      # Mount for telegraf configuration
      - /etc/telegraf:/etc/telegraf
      # Mount for Docker API access
      - /var/run/docker.sock:/var/run/docker.sock

  # DATABASE
  influxdb:
    # Full tag list: https://hub.docker.com/r/library/influxdb/tags/
    image: 127.0.0.1:5000/influxdb
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    volumes:
      # Mount for influxdb data directory
      - /influxdb-data:/var/lib/influxdb
      # Mount for influxdb configuration
      - /etc/influxdb/config:/etc/influxdb
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"

volumes:
  chronograf-data:
  kapacitor-data:
  influxdb-data: