---
- name: TEST MANAGER
  hosts: manager
  remote_user: sitruk_m
  become: yes
  roles:
     - docker_swarm
     - docker_registry
     - { role: docker_tickstack, tags: [ 'docker_tickstack' ] }

- name: TEST WORKERS
  hosts: workers
  remote_user: sitruk_m
  become: yes
  roles:
   - docker_swarm

...
