---
- name: TEST MANAGER
  hosts: manager
  remote_user: thomas_s
  become: yes
  roles:
     - docker_swarm
     - docker_registry
     - docker_tickstack

- name: TEST WORKERS
  hosts: workers
  remote_user: thomas_s
  become: yes
  roles:
   - docker_swarm
   - docker_tickstack

...
