---
# tasks file for docker_tickstack
- name: Synchronization of src on the control machine to dest on the remote hosts
  synchronize:
    src: tickstack/
    dest: /home/sitruk_m/tickstack/
  when: ansible_host == '172.16.226.14'

- name: Build chronograf image and push it to regitry
  when: ansible_host == '172.16.226.14'
  become: yes
  docker_image:
    path: ./tickstack/chronograf/
    name: 127.0.0.1:5000/chronograf
    tag: latest
    push: yes

- name: Build influxdb image and push it to regitry
  when: ansible_host == '172.16.226.14'
  become: yes
  docker_image:
    path: ./tickstack/influxdb/
    name: 127.0.0.1:5000/influxdb
    tag: latest
    push: yes

- name: Build kapacitor image and push it to regitry
  when: ansible_host == '172.16.226.14'
  become: yes
  docker_image:
    path: ./tickstack/kapacitor/
    name: 127.0.0.1:5000/kapacitor
    tag: latest
    push: yes

- name: Build telegraf image and push it to regitry
  when: ansible_host == '172.16.226.14'
  become: yes
  docker_image:
    path: ./tickstack/telegraf/
    name: 127.0.0.1:5000/telegraf
    tag: latest
    push: yes

- name: deploy tickstack
  shell: 'docker stack deploy --compose-file /home/sitruk_m/tickstack/docker-compose.yml tick'
